spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fashionboot?createDatabaseIfNotExist=true
    username: matheus
    password: root
#    data: classpath:data.sql
#    schema: classpath:data.sql
#    initialization-mode: always
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


